import CardProduct from "@/components/CardProduct";
import Searchbox from "@/components/Searchbox";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Realcommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="md:w-1/2 m-auto">
        <div className="mx-2 my-5 md:my-6">
          <Searchbox />
        </div>

        <div>
          <div className="mx-2 my-5 md:my-6">
            <CardProduct />
          </div>
        </div>
      </main>
    </>
  );
}
