import Searchbox from "@/components/Searchbox";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Realcommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="md:w-1/2 m-auto">
        <div className="my-10">
          <Searchbox />
        </div>
      </main>
    </>
  );
}
