import CardProduct from "@/components/CardProduct";
import Searchbox from "@/components/Searchbox";
import { products } from "@/redux/features/actions/products";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  const product = useSelector((state) => state.product);
  const productData = product?.data?.data?.products;

  useEffect(() => {
    dispatch(products());
  }, []);

  return (
    <>
      <Head>
        <title>Realcommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="md:w-1/2 m-auto">
        <div className="mx-2 my-5 md:my-6">
          <Searchbox />
        </div>

        <div>
          <CardProduct data={productData} />
        </div>
      </main>
    </>
  );
}
