import React from "react";
import Head from "next/head";
import { useSelector } from "react-redux";

const Auth = () => {
  const auth = useSelector((state) => state.auth);
  console.log(auth);

  return (
    <>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Hello world</h1>
      </div>
    </>
  );
};

export default Auth;
