import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { useForm } from "react-hook-form";
import { authSignIn, authSignUp, login } from "@/redux/features/auth/authSlice";
import { useRouter } from "next/router";

const Auth = () => {
  const router = useRouter();
  const dispatch = useDispatch();
  const [showLogin, setShowLogin] = useState(true);
  const auth = useSelector((state) => state.auth);
  console.log(auth);

  const { register, watch, handleSubmit } = useForm();

  const onSubmit = () => {
    const data = {
      name: watch("username"),
      email: watch("email"),
      password: watch("password"),
    };

    if (showLogin) {
      dispatch(authSignIn(data));
    } else {
      dispatch(authSignUp(data));
    }
  };

  const alert = () => {
    if (auth.isAdd) {
      return (
        <div
          className="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400"
          role="alert"
        >
          <span className="font-medium">Register success, please login!</span>
        </div>
      );
    }

    if (auth.isLogin === "false") {
      return (
        <div
          className="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
          role="alert"
        >
          <span className="font-medium">Error</span> {auth.message}
        </div>
      );
    }

    if (auth.isLogin === "true") {
      return (
        <div
          className="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400"
          role="alert"
        >
          <span className="font-medium  animate-pulse">
            Login success, redirecting!
          </span>
        </div>
      );
    }
  };

  const togleShowLogin = () => {
    if (showLogin) {
      return (
        <div>
          <span>Register</span>
        </div>
      );
    } else {
      return (
        <div>
          <span>Login</span>
        </div>
      );
    }
  };

  useEffect(() => {
    if (auth.isLogin === "true") {
      setTimeout(() => {
        router.push("/");
      }, 3000);
    }
  }, [auth.isLogin]);

  return (
    <>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center w-full h-h1">
        <div className="bg-gray-50 dark:bg-darkCard w-96 py-8 px-6 rounded-lg shadow-bottom">
          <div className="mb-5">
            <h1 className="font-semibold text-lg md:text-2xl">
              Login to your account!
            </h1>
          </div>

          <div>
            {alert()}
            <form
              className="flex flex-col gap-3"
              onSubmit={handleSubmit(onSubmit)}
            >
              {showLogin ? null : (
                <div className="flex flex-col gap-1">
                  <label htmlFor="username" className="text-sm md:text-md">
                    Username
                  </label>
                  <input
                    {...register("username")}
                    type="name"
                    className="py-2 px-3 rounded-lg"
                    placeholder="username"
                    required
                  />
                </div>
              )}
              <div className="flex flex-col gap-1">
                <label htmlFor="email" className="text-sm md:text-md">
                  Email
                </label>
                <input
                  {...register("email")}
                  type="email"
                  className="py-2 px-3 rounded-lg"
                  placeholder="user@example.com"
                  required
                />
              </div>

              <div className="flex flex-col gap-1">
                <label htmlFor="password" className="text-sm md:text-md">
                  Password
                </label>
                <input
                  {...register("password")}
                  type="password"
                  className="py-2 px-3 rounded-lg"
                  placeholder="password"
                  required
                />
              </div>

              <div>
                <button
                  type="submit"
                  className="w-full bg-darkFg p-2 rounded-lg"
                >
                  <p className="text-gray-50">Continue</p>
                </button>
              </div>

              <div className="text-center">
                <p className="text-sm">
                  Create account ?{" "}
                  <button
                    type="button"
                    onClick={() => {
                      setShowLogin(!showLogin), dispatch(login());
                    }}
                  >
                    <div className="font-bold">{togleShowLogin()}</div>
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default Auth;
